version: "3.9"
services:
  node:
    build:
      context: ./
    ports:
      - 3000:80
    volumes:
      - ./.env:/app/.env
    environment:
      - NODE_ENV=development
      - PORT=80
    platform: linux/amd64
